checks:
  php: true

filter:
  paths:
    - "src/*"

tools:
  external_code_coverage:
    timeout: 900    # Timeout in seconds.
    runs: 2         # How many code coverage submissions Scrutinizer will wait

build:
  image: default-bionic
  environment:
    php: 8.1.2