name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Create runtime cache folder
      run: mkdir -v -p -m 777 tests/runtime/cache

    - name: Create sqlite folder
      run: mkdir -v -p -m 777 tests/runtime/sqlite && touch tests/runtime/sqlite/database.db

    - name: Execute Tests
      run: vendor/bin/phpunit tests --colors=always --coverage-clover=coverage.clover
      env:
        XDEBUG_MODE: coverage
      
    - name: Upload coverage reports to Codecov
      continue-on-error: true
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.clover
